### ISSUE TITLE
Do these containers follow the "latest" tag?

### ISSUE THREAD

**Issue by boredsquirrel** [ublue-os/toolboxes#105]
[This issue](https://github.com/89luca89/distrobox/issues/1338) describes the big problem with using versioned Distrobox containers as an OS with a package manager.

As the concept is doing all changes manually as the user, and not during the image creation, doing a system upgrade (version upgrade) is difficult.

Do these containers fix this issue in some way? Does this even work?

**Comment by m2Giles** [comment]
Fedora and Ubuntu are tied to versioned podman images.

Fedora from toolbx repo and Ubuntu from docker hub. When new releases occur we bump the version. Fedora will bump every 6ish months and Ubuntu every 2ish years. However we only really use the latest tag.

While Distroboxes can be turned into pets, you likely shouldn't treat them fully like pets. You noted that doing a major version upgrade doesn't quite work. And I would agree with that. Distrobox assemble is a tool to help you declare your distrobox and rebuild it quickly. For my distroboxes I usually do this weekly.

On bluefin/Aurora we consume these images using quadlets. With quadlets we have the distrobox recreated on each login and image updates happen daily.
