### ISSUE TITLE
Make a powershell toolbox

### ISSUE THREAD

**Issue by castrojo** [ublue-os/toolboxes#11]
I'd like to see if people would dig a dedicated powershell terminal, so if you've got Windows friends that can help, that'd be awesome!

For implementation please use the `ghcr.io/ublue-os/wolfi-base` container and add `powershell` to its package list. 

Not sure what the rest of the Containerfile looks like though.

**Comment by noelmiller** [comment]
You could probably expand the scope to common Microsoft tooling folks would use. 

A couple suggestions would be Azure CLI and .Net Core.

**Comment by lambdaclan** [comment]
Hello, I would like to work on this task. I have a preliminary pull request ready for the initial review. I am happy to add new packages if required but for now I have added PowerShell, dotnet core and Azure CLI. 

Furthermore, I am not sure how people tend to use these toolboxes but if we assume that no shell customizations are in place (inherited from home directory) we could add some blink to the shell. Things like [Oh My Posh] (https://ohmyposh.dev/) [posh-git](https://github.com/dahlbyk/posh-git) and [PSFzf](https://github.com/kelleyma49/PSFzf) are popular amongst PowerShell users. For even more have a look at this [repo](https://github.com/janikvonrotz/awesome-powershell).

Feel free to ping me if any additions or changes are required!

**Comment by castrojo** [comment]
Thanks for submitting the pull request, I'll merge it when it builds! Since no one's really claimed it, then feel free to provide whatever UX you feel people would like!

Check out the bluefin-cli toolbox for conventions on where we're putting the scripts, etc. This will be an awesome addition to the collection, thanks for working on this!

**Comment by castrojo** [comment]
I'll set up the CI!
