### ISSUE TITLE
Switch to uutils by default

### ISSUE THREAD

**Issue by castrojo** [ublue-os/toolboxes#29]
We might as well burn all the ships and switch to `uutils`.

**Comment by m2Giles** [comment]
`uutils` and `coreutils` conflict.

`coreutils` is a dependency for brew. We can see if this is a hard dependency or a choice.

**Comment by EyeCantCU** [comment]
If that's the case, the package for `uutils` can be updated to replace `coreutils` and can be marked as a provider of `coreutils`. Will get a PR up for that in Wolfi

**Comment by castrojo** [comment]
All your work just landed upstream. Rebuilt and tested, we are now on uutils by default. THANK YOU!
