### ISSUE TITLE
Add zoxide as cd

### ISSUE THREAD

**Issue by castrojo** [ublue-os/toolboxes#45]
What do we think about just aliasing cd to zoxide? 

https://github.com/ajeetdsouza/zoxide

**Comment by m2Giles** [comment]
we are currently using eza as ls.

We could grab this, fd, rg, and bat?

**Comment by m2Giles** [comment]
there is some issues with bat, but eza, zoxide, rg, and fd are now in the image.

**Comment by m2Giles** [comment]
#47
