### ISSUE TITLE
Distrobox update error when running ujust update

### ISSUE THREAD

**Issue by d1on** [ublue-os/toolboxes#73]
When running ujust update, the following error occurs:

```
── 09:44:39 - Distrobox ────────────────────────────────────────────────────────
 Upgrading ubuntu...
distrobox: Installing basic packages...
/usr/bin/apt-get
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  ubuntu-advantage-tools ubuntu-pro-client-l10n
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
 Upgrading bluefin-cli...
/sbin/su-exec
distrobox: Installing basic packages...
/usr/local/bin/xdg-open
BusyBox v1.36.1 (2024-02-08 15:48:36 UTC) multi-call binary.

Usage: su [-lmp] [-s SH] [-] [USER [FILE ARGS | -c 'CMD' [ARG0 ARGS]]]

Run shell under USER (by default, root)

	-,-l	Clear environment, go to home dir, run shell as login shell
	-p,-m	Do not set new $HOME, $SHELL, $USER, $LOGNAME
	-c CMD	Command to pass to 'sh -c'
	-s SH	Shell to use instead of user's default
distrobox: Setting up devpts mounts...
distrobox: Setting up read-only mounts...
distrobox: Setting up read-write mounts...
/usr/bin/entrypoint: line 1459: container_user_name: parameter not set
Error: An error occurred
su-exec: -S: No such file or directory

```

```
── 09:44:57 - Summary ──────────────────────────────────────────────────────────
System update: OK
distrobox: IGNORED
Firmware upgrades: OK
Flatpak: OK
Brew: OK
Visual Studio Code extensions: OK
```

**Comment by m2Giles** [comment]
Yeah, we can remove the additional packages from our quadlets.

**Comment by m2Giles** [comment]
#74

**Comment by evanphilip** [comment]
Thank you for the quick pull request to resolve https://github.com/ublue-os/toolboxes/issues/73! Sadly, @m2Giles https://github.com/ublue-os/toolboxes/pull/74 is breaking the ability to start the container without internet. 

I had previously assumed the _only_ thing preventing the container from starting without internet was `--additional-packages`. However, I was wrong. The `bluefin-cli` image does not have the packages `man` and `pinentry`. When `/usr/bin/entrypoint` executes the following lines
```
for dep in ${dependencies}; do
        ! command -v "${dep}" > /dev/null && missing_packages=1 && break
done
```
`missing_packages` causes all the dependencies to be reinstalled, even if we don't provide any  `--additional-packages`. This prevents the container from starting without internet.

I propose we keep the current changes, but create a patch in `/toolboxes/bluefin-cli/Containerfile.bluefin-cli` like before to prevent checking for missing packages.

**Comment by m2Giles** [comment]
If the packages are available in Wolfi we can add them to the Wolfi toolbox.

If they are not available, the check is just seeing if a command of that name exists so maybe a dummy command will work instead.

**Comment by evanphilip** [comment]
The package `man` is available as `man-db` in Wolfi, so it can be added to the toolbox.
`pinentry` is not available in Wolfi. Creating the dummy command sounds like a great idea! I am hesitant to submit a pull request since I can't (easily) generate images from my fork, so I can't test changes directly to the toolbox image.

**Comment by castrojo** [comment]
OK try now!
