### ISSUE TITLE
Topgrade attempts to upgrade bluefin-cli via distrobox and fails

### ISSUE THREAD

**Issue by tbjers** [ublue-os/toolboxes#88]
When running `ujust update` the Topgrade process attempts to perform an in-place upgrade of the bluefin-cli container. The upgrade process fails with the following output:

```
── 16:11:40 - Distrobox ────────────────────────────────────────────────────────
 Upgrading bluefin-cli...
/sbin/su-exec
distrobox: Installing basic packages...
/usr/local/bin/xdg-open
BusyBox v1.36.1 (2024-03-27 13:51:06 UTC) multi-call binary.

Usage: su [-lmp] [-s SH] [-] [USER [FILE ARGS | -c 'CMD' [ARG0 ARGS]]]

Run shell under USER (by default, root)

        -,-l    Clear environment, go to home dir, run shell as login shell
        -p,-m   Do not set new $HOME, $SHELL, $USER, $LOGNAME
        -c CMD  Command to pass to 'sh -c'
        -s SH   Shell to use instead of user's default
distrobox: Setting up devpts mounts...
distrobox: Setting up read-only mounts...
distrobox: Setting up read-write mounts...
/usr/bin/entrypoint: line 1465: container_user_name: parameter not set
Error: An error occurred
su-exec: -S: No such file or directory
```

[Jorge mentioned](https://universal-blue.discourse.group/t/the-bluefin-cli-container/704/7) that we do not want to perform this in-place upgrade on this container as it is built via CI.

**Comment by castrojo** [comment]
I think we'll need to just adjust the topgrade.toml to ignore this box. I'll try to find time investigating.

**Comment by m2Giles** [comment]
We'll need to get real su for the wolfi boxes. BusyBox su is causing this problem most likely.

**Comment by tbjers** [comment]
Yeah, BusyBox is a bit quirky. The integrated `less` command is atrocious, I always wipe it and install directly from `apk`.

**Comment by m2Giles** [comment]
This seems to be fixed now:
![image](https://github.com/ublue-os/toolboxes/assets/69128853/3449862f-61a9-41fd-87d7-b6b47af3dadb)
